# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.5
_src_path: gh:algorandfoundation/algokit-python-template
author_email: 93087419+tactboogie@users.noreply.github.com
author_name: tactboogie
contract_name: digital_marketplace
deployment_language: python
preset_name: production
project_name: digital_marketplace

